### ISSUE TITLE
Invalid parameter not satisfying: mapping

### ISSUE THREAD

**Issue by dingari** [darlinghq/darling-stub-gen#3]
Running the application produces an error "Invalid parameter not satisfying: mapping" in `MKMachOImage`'s `initWithName`.

The `memoryMap` [passed in](https://github.com/darlinghq/darling-stub-gen/blob/551cfd612c4bcc82003c7fe1d7d1017610a4b8b8/src/main.m#L47) is `nil`. Am I missing something obvious? What's the role of `argumentParser.inputUrl`?

```
./darling-stub-gen /tmp/libraries/System/Library/Frameworks/CoreGraphics.framework ~/CoreGraphics
2023-01-06 10:23:07.210 darling-stub-gen[92593:1140563] *** Assertion failure in -[MKMachOImage initWithName:flags:atAddress:inMapping:error:], MKMachO.m:45
2023-01-06 10:23:07.212 darling-stub-gen[92593:1140563] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: mapping'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000192824418 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000019236eea8 objc_exception_throw + 60
	2   Foundation                          0x0000000193764a60 -[NSCalendarDate initWithCoder:] + 0
	3   MachOKit                            0x000000010289c080 -[MKMachOImage initWithName:flags:atAddress:inMapping:error:] + 172
	4   darling-stub-gen                    0x0000000102534270 main + 284
	5   dyld                                0x000000019239fe50 start + 2544
)
libc++abi: terminating with uncaught exception of type NSException
[1]    92593 abort      ./darling-stub-gen  ~/CoreGraphics
```

**Comment by CuriousTommy** [comment]
>  There is no `inputUrl` or `outputUrl` in `DLArgumentParser`

Actually, it does exist there.

https://github.com/darlinghq/darling-stub-gen/blob/551cfd612c4bcc82003c7fe1d7d1017610a4b8b8/src/DLArgumentParser.m#L45-L51

But I think your issue might be due to you using a relative path (`~/CoreGraphics`). I recall running into issues when using a relative path.

**Comment by dingari** [comment]
Ah okay, I missed those methods!

I wasn't invoking the program with any relative paths, though. I was invoking it with these arguments:
```
/tmp/libraries/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics /Users/<my_name>/CoreGraphics
```

But you can just delete this PR and close it if it isn't an issue.

**Comment by dingari** [comment]
Yes, I noticed!
